[palettes.pastel]
directory = "#89CFF0"
git_branch = "#FFB6C1"    
git_status = "#333333"    
time = "#89CFF0"          
palette = "pastel"

format = """
$username$hostname$directory\
$git_branch$git_commit$git_state$git_status\
$time$line_break$character
"""

[directory]
truncation_length = 3
truncate_to_repo = false
format = " [ $path]($style)[$read_only]($read_only_style) "
style = "#89CFF0"
read_only = " "
read_only_style = "red"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "#FFB6C1"
truncation_length = 30
truncation_symbol = "…"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "#333333"
conflicted = "⚡"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
up_to_date = ""
untracked = "?"
stashed = "$"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"

[line_break]
disabled = false

[character]
success_symbol = " [](bold #89CFF0)"  # Пиксельная стрелка вправо (успех, голубая)
error_symbol = " [⊘︎ ](bold #FFB6C1)"    # Пиксельная стрелка вниз (ошибка, розовая)
